### ISSUE TITLE
Requesting update to JSON schema

### ISSUE THREAD

**Issue by jwbaker-mitre** [center-for-threat-informed-defense/adversary_emulation_library#22]
Changes need to be made to the JSON schema to reflect the following changes to the emulation plan YAML.

1. Overall plan information within the YAML (Required field)
```
- emulation_plan_details:
    id: 123700e5-44c8-4894-a409-6484992c8846
    adversary_name: FIN6 Adversary Emulation Plan
    adversary_description: FIN6 is a financially motivated cyber crime group known for stealing credit card data and performing ransomware attacks.
    attack_version: 7.2
    format_version: 1.0
```

2. Cleanup commands were added to more closely match CALDERA yaml (Optional field)
```
        payloads: 
        - wce.exe
        cleanup: |
          del "#{output_file}" >nul 2>&1
```
